### ISSUE TITLE
BioSample missing in germline schema?

### ISSUE THREAD

**Issue by oliverdrechsel** [bihealth/biomedsheets#7]
Which of the columns in germline tsv translates to BioSample?   

- `patientID` would go to `BioEntity`
- cancer tsv has `sampleName` for this
- should `sampleName` be introduced to germline tsv as well?

**Comment by holtgrewe** [comment]
Sample name is there so you can have `T1` and `M1` to have your own coding for differentiating primary tumors and metastatic tumors. Added this in documentation of #8

**Comment by oliverdrechsel** [comment]
This would be part of the cancer schema, where sample name is already designed. But as written in the header - the Germline schema seems to not contain a sample name column or JSON field.
